README.md, hsv_dot_beer/config/local.py
1. Update readme to suggest Python 3.6 instead of 3.7
2. Change the directory passed to nose to be the git repo root, not `hsv_dot_beer/`
3. Switch back to the nose default of capturing stdout and logging
=> Expand test coverage to cover all apps

beers/test/test_views.py, events/test/test_views.py, hsv_dot_beer/config/common.py, hsv_dot_beer/permissions.py, hsv_dot_beer/test_permissions.py, hsv_dot_beer/users/test/test_views.py, hsv_dot_beer/users/views.py, taps/test/test_views.py, venues/test/test_views.py
New access control rules:
1. Anybody can read anything that's exposed in the API
2. Only staff users (those who can access the admin page) can
write to anything.
Fixes #13.
=> Open up read-only access to all users

tap_list_providers/parsers/thenook.py, tap_list_providers/test/test_thenook.py
These indicate serving temperature, which we don't particularly
care about at the moment.
Fixes #45
=> Drop trailing asterisks from The Nook's list

tap_list_providers/parsers/untappd.py
Das Stahl Bierhaus uses CST/CDT in its updated timestamps
=> Handle non-UTC timestamps from untappd

tap_list_providers/parsers/untappd.py
Currently at DSB, tap 24 (Andromeda Ambrosia, a ginger beer from Alabaster) is missing ABV.
Tap 22 (Primordial Noir) is missing location:
=> Catch missing location and ABV data in untappd

tap_list_providers/base.py
That way, if a beer has metadata that doesn't match but names
conflict, we won't get an integrity error.
=> Stop looking up the beer with defaults

tap_list_providers/parsers/untappd.py, venues/fixtures/venues.json
Fixes #98 by:
1. Making the category comparison case-insensitive
2. Changing the category comparison to use the `section` div heading rather than the `menu-title` h1.
=> Work around Yellowhammer reformatting its menu

tap_list_providers/base.py
1. Don't bother validating URL fields if it's already set to the same value that's passed in to `look_up_beer()`
2. If we run into the heroku free redis limit while parsing beers, fall back to looking up untappd metadata synchronously.
=> Silence a couple warnings and catch redis limit in parsing code

Pipfile.lock
PyYAML finally released a version that fixes the security vuln
it has had for years (unsafe loader as default), so let's go ahead
and version bump everything while we're at it.
=> Version bump dependencies

bin/entry-point.sh
The heroku VM has 8 cores. Let's not use them all in the hopes of
saving RAM.
If this still isn't enough, we can go back to 2.
=> Scale back workers to 4 processes

tap_list_providers/parsers/stemandstein.py
Currently, Avondale Vanillaphant Porter is on tap and doesn't
have a color assigned. This is a bad thing as their site assumes
it's `#000000`, which is so bad it isn't even wrong.
To test, switch to master and run `./manage.py parsestemandstein` and observe the exception. Switch to this branch and observe success.
Fixes #184
=> Catch missing color from the Stem and Stein

Pipfile.lock, azure-pipelines.yml, hsv_dot_beer/config/local.py, hsv_dot_beer/config/production.py
- Bump Django CORS headers to 3.0.1
- Add HTTPS schema to CORS whitelist
- Change azure build setup to stop modifying the Pipfile, which is what caused the tests in #193 to fail.
=> Version bump

tap_list_providers/parsers/stemandstein.py, tap_list_providers/test/test_stemandstein.py
Because The Stem and Stein doesn't include tap numbers in its site,
we automatically assign them taps 1 through _N_. Because _N_ is
variable (currently at 10, max seen is 18), we should make sure
we drop unused taps at the end of each processing run.
Otherwise, we have stale data (e.g. beers that were removed weeks
ago).
Fixes #219.
=> Delete unused Stem and Stein taps

azure-pipelines.yml
1. Split pep8 and django tests into separate `script` blocks
2. Upgrade to python 3.7
3. Disable the pipenv spinner to hopefully make the logs way shorter
4. Don't use pipenv or docker for the pep8 run for speed
=> Improve Azure pipeline runs

beers/filters.py, beers/test/test_views.py
`/api/v1/beers/?taps__venue__slug=otbx` to get beers at OTBX, for example.
Fixes #236 in a band-aid way until django-rest-framework-filters 1.0
comes out.
=> Allow filtering beers by venue slug

beers/models.py, beers/test/test_merge.py
If two beers to be merged have the same venue + size combo, take
the most cautious route possible and discard prices from the other
beer for that venue.
Any issues with inconsistent data will resolve themselves within
an hour of moderation anyway.
Fixes #239.
=> Save prices when merging beers

docker-compose.yml
By copying the volume, we only need to restart the image rather
than rebuild it every time we change worker code.
Doesn't effect anything in prod but makes dev way easier.
=> Fix need to rebuild image every time tasks change

hsv_dot_beer/config/production.py
`\w` is equivalent to `[a-zA-Z0-9_]`. Note that hyphens aren't
included.
Also go ahead and switch the regex to be more specific.
I think this does what #252 was trying to do.
=> Fix CORS regex to account for hyphens

tap_list_providers/parsers/stemandstein.py, tap_list_providers/test/test_stemandstein.py
It's relatively easy to parse, so let's save the ABV & brewery location if given.
Fixes #254
=> Save beer ABV and brewery location if given from Stem & Stein

venues/fixtures/venues.json
They're small and usable.
- Liquor Express
- Open Bottle
Addresses #251
=> Add beer logos

venues/fixtures/venues.json
Now every logo is usable except for Stem & Stein, which doesn't host a valid (read: not white on transparent) logo anywhere.
Addresses #251.
=> More logos

Pipfile, Pipfile.lock, hsv_dot_beer/config/production.py
@doismellburning seems to have stumbled upon a fix in
https://github.com/doismellburning/emporium/commit/14f88931b4ccbc5c43ee62823dd3eaabebe1cdd9
so let's go with that.
=> Switch to django-bmemcached for the backend

tap_list_providers/tasks.py, tap_list_providers/test/test_tweets.py, tap_list_providers/test/test_twitter_api.py, tap_list_providers/twitter_api.py
Subclass `twitter.api.Api` and override `PostUpdates()` to properly thread tweets.
Fixes #277.
=> Fix Twitter threading

tap_list_providers/test/test_twitter_api.py, tap_list_providers/twitter_api.py
Fixes #280 by rewriting the way we preserve line breaks:
1. Split the tweet up by lines.
2. If a given line is too long to fit in a single tweet, take whatever we've accrued so far and save that as a tweet, then pass the given line to upstream's split by whitespace, then drop whatever it gives us into the series of tweets (after appending continuation to each line).
3. If the accrued current tweet plus the given line is too long, save the accrued tweet plus continuation to the series of tweets and then keep the given line as the start of the next tweet.
4. Otherwise, append a line break to the accrued tweet followed by the given line.
Once done looping over the lines, save the accrued tweet as the last one.
=> Preserve line breaks when threading tweets

tap_list_providers/fixtures/scheduled_tasks.json
All it does is cause integrity errors
=> Drop unneeded model from scheduled tasks fixture

Pipfile, Pipfile.lock
They changed the syntax between 0.2.4 and 0.3.0 in a breaking
manner, so temporarily downgrade while I investigate the fix.
=> Downgrade django-bmemcached to 0.2.4

venues/fixtures/venues.json
Since the fest is over for the year, we should drop it from our venues list.
It's already gone from the prod DB.
=> Remove the Von Brewski Beer Festival

tap_list_providers/parsers/untappd.py
This seems to be relatively new, but Untappd is escaping dollar signs.
Formal testing to come later; I wanted to get this out because we missed Black is Beautiful from YH.
=> Strip stray backslashes from Untappd

tap_list_providers/base.py, tap_list_providers/test/test_base.py
Also add some more common brewery endings and strip ® and ™ from brewery names (looking at you, Rocket Republic).
Fixes #336.
=> Prevent URLs from sneaking in as Twitter handles

tap_list_providers/base.py, tap_list_providers/test/test_base.py
So that way `Yazoo Brewing Company Hefeweizen` with brewery `Yazoo`
doesn't become `Brewing Company Hefeweizen`.
Fixes #325
=> Fix the case where stripping out the brewery name breaks the beer

tap_list_providers/parsers/taplist_io.py
They moved the API to api.taplist.io
=> Use new URL for taplist.io

hsv_dot_beer/test_migration_missing.py
This way stuff like #366 won't have to happen and we'll catch during test/review.
=> Create a test for ensuring that we didn't forget to commit migrations

tap_list_providers/parsers/digitalpour.py
DigitalPour is currently down (503 error), so let's raise the right
exception in that case.
=> Raise a request exception on digitalpour outages

tap_list_providers/base.py, tap_list_providers/tasks.py
1. Adds `arryved_pos` to the imports in `tap_list_providers/tasks.py` so the subclass logic can find this parser.
2. Fix typo (prover -> provider)
=> Fix scheduled parsing for Arryved POS Menus

tap_list_providers/parsers/arryved_menu.py, tap_list_providers/test/test_arryved_menu.py, venues/fixtures-al/venues.json
Also clean up unused taps at the end of processing the venue.
Reduces tap count from 21 to 17 and there are zero wines on tap.
=> Drop wine serving sizes from Tallulah fixture

tap_list_providers/test/test_twitter_api.py, tap_list_providers/twitter_api.py
If two messages being joined are 278-279 characters without the CRLF, the tweet building logic created invalid tweets because it didn't consider the line length in the validation.
Fixes #378
=> Fix line length check when splitting long tweets

tap_list_providers/base.py, tap_list_providers/test/test_untappd.py
If you run the test in January, the existing version passes.
If you run it in Februrary or later, it fails.
Rather than muddle with freezegun, just document it and move on.
=> Fix off-by-one-year error in untappd test

hsv_dot_beer/config/common.py
In March 2021, Heroku deprecated redis 4.x and 5.x, and the easy way to
upgrade is to attach a new instance, switch over our config, and talk to it.
However, because the web UI has no way to control what name the new redis instance
attaches as, we have to deal with different names per env.
Switching instances like this means we'll lose transient data (i.e.
any pending tweets or untappd lookups will get lost). That's harmless
because anything lost will get picked up on the next scheduled tweet
check or API lookup.
Also this means we can **eventually** connect over TLS, which, yay.
=> Update configs to use redis 6.x

Dockerfile, Pipfile, Pipfile.lock, hsv_dot_beer/users/test/test_views.py, tap_list_providers/parsers/stemandstein.py
We might as well get current.
The only change is using `html.unescape()` directly rather than
pulling from `html.parser.HTMLParser().unescape()`. I'm not sure
how that worked in the past.
=> Upgrade to Python 3.9

Dockerfile, package-lock.json, package.json, setup_node_16.sh
There's a security advisory for browserslist that dependabot can't fix for us, so we need to do that as well.
Since node 15 is no longer supported, let's upgrade to 16.
=> Upgrade to node 16 and bump all packages

tap_list_providers/parsers/untappd.py
Goat Island is offering a "case of 12 oz beers" as a size. This is
bogus.
=> Skip unparseable sizes

hsv_dot_beer/config/common.py
Silences a warning introduced by Django 3.2. Fortunately, it doesn't require any migrations.
Fixes #426.
=> Set the default auto field type to AutoField
