Pipfile.lock
=> Version bump dependencies

tap_list_providers/example_data/the_nook.html, tap_list_providers/management/commands/parsethenook.py, tap_list_providers/parsers/thenook.py, tap_list_providers/test/test_thenook.py
=> Add parser and tests for The Nook

tap_list_providers/parsers/untappd.py
Handle the case where location doesn't match between venues
Fixes #46
=> Fix integrity error in Untappd parser

beers/filters.py, beers/test/test_views.py, beers/views.py, docs/beers/beers.md, hsv_dot_beer/config/common.py
Adds filtering of beers by the fields in #51.
Fixes #51.
=> Filter beers

docs/venues/venues.md, hsv_dot_beer/config/common.py, venues/filters.py, venues/test/test_views.py, venues/views.py
=> Add filtering for venues

docs/tap_list_providers/parsers.md, mkdocs.yml
=> Add documentation on how to write tap list providers

beers/filters.py, beers/serializers.py, beers/test/test_views.py, beers/views.py
1. Add a `venues` attribute to the beer list
2. Add a detail route: `/api/v1/beers/<pk>/placesavailable/`
=> Add places where you can find a beer

beers/serializers.py, venues/test/test_views.py, venues/views.py
=> Add detail routes to venues for both style and category

Pipfile, Pipfile.lock, hsv_dot_beer/config/common.py, hsv_dot_beer/config/local.py, hsv_dot_beer/config/production.py
Basic CORS support.
@mjcarroll will have to configure it for codepen.
=> Cross-origin request sharing

Pipfile.lock
Pipenv under WSL somehow didn't handle the deps correctly,
meaning that redis is not installing. Fix that.
=> Fix lock file

bin/entry-point.sh, docker-compose.yml
This should free up some RAM on the heroku dyno
=> Launch celery beat from within the worker

venues/fixtures/venues.json
=> Add Blue Pants to our list of venues

beers/serializers.py
=> Catch redis telling us no and don't return 500

azure-pipelines.yml, tap_list_providers/test/test_digitalpour.py, tap_list_providers/test/test_parse_example_data.py, tap_list_providers/test/test_stemandstein.py, tap_list_providers/test/test_taphunter.py, tap_list_providers/test/test_thenook.py, tap_list_providers/test/test_untappd.py
=> Set up CI with Azure Pipelines

beers/admin.py, setup.cfg
1. Add manufacturer to the beer list in the admin view
2. Allow searching by beer and manufacturer name
3. Add action to merge beers:
- select a number of beers to merge
- from the "Action" drop-down, choose "Merge beers"
- Click Go
4. Add searching by name to manufacturer admin view
5. Add merging to manufacturer admin view
=> Beef up beer and manufacturer admin views

tap_list_providers/tasks.py
In the case of transient network failures, requests will raise various subclasses of `RequestException`. We don't really care which one it is, so just retry in about 10 minutes.
=> Automatically retry parsing provider on HTTP/JSON failure

beers/test/test_merge.py, setup.cfg, tap_list_providers/parsers/stemandstein.py, tap_list_providers/test/test_stemandstein.py, venues/test/test_views.py
Fixes #122.
I'll manually fix those three busted beers.
=> Fix Stem and Stein brewery guessing logic

tap_list_providers/base.py, tap_list_providers/example_data/967.html, tap_list_providers/example_data/liquor_express.json, tap_list_providers/example_data/stem_and_stein_main.html, tap_list_providers/parsers/stemandstein.py, tap_list_providers/test/test_stemandstein.py, tap_list_providers/test/test_taphunter.py
We don't care about leading or trailing spaces, so kill them
=> Strip external whitespace from beer and manufacturer before parsing

tap_list_providers/parsers/digitalpour.py, tap_list_providers/test/test_digitalpour.py
=> Save brewery twitter handles from digitalpour if given

beers/admin.py
Open the admin page (/admin/beers/style/), select the styles you want to dump, and choose export to CSV.
Note that Excel will likely barf at Unicode. Not our problem.
Fixes #159.
=> Add method to dump all beer styles to CSV

beers/admin.py
This might make it slightly easier to moderate the duplicate beers.
=> Export beers admin list as a CSV

beers/filters.py, beers/test/test_views.py
=> Filter out duplicates in on tap lookup

venues/fixtures/venues.json
Title says it all.
After merging and deploying, open a shell on prod and run `./manage.py loaddata venues/fixtures/venues.json`.
Fixes #137.
=> Restore madison taproom

beers/admin.py, beers/models.py, beers/templates/beers/merge_styles.html, beers/test/test_merge_style.py, beers/views.py, hsv_dot_beer/urls.py, tap_list_providers/base.py
Add a simple form for merging styles that lets you choose which style to keep.
Once this is merged, I'll port this form over to beers and manufacturers to make them easier to moderate.
Screenshots:
- Admin view
- The form
- After
=> Style admin improvements

tap_list_providers/base.py, tap_list_providers/test/test_base.py
=> Filter out duplicate manufacturers in parser lookup

hsv_dot_beer/config/production.py, hsv_dot_beer/wsgi.py
=> Force SSL with cloudflare + heroku

beers/views.py, venues/views.py
=> Cache beers and venues for 5 minutes

beers/views.py
Returns the 10 most relevant styles, beers, and manufacturers for a search term.
Relevancy is determined by number of taps occupied, number of beers, and then alphabetical order as a tiebreaker.
Examples:
`?search=strai`
```json
{
"beers": [
{
"name": "420 Strain Mango Kush",
"taps": 1,
"alternate_names": [],
"manufacturer": "SweetWater"
},
{
"name": "Straight to Ale Chill Pils",
"taps": 0,
"alternate_names": [],
"manufacturer": "Straight To Ale"
},
{
"name": "420 Strain G13 IPA",
"taps": 0,
"alternate_names": [],
"manufacturer": "SweetWater Brewing Company"
},
{
"name": "420 Strain: Mango Kush",
"taps": 0,
"alternate_names": [],
"manufacturer": "SweetWater Brewing Company"
}
],
"styles": [],
"manufacturers": [
{
"name": "Straight To Ale",
"beers": 61,
"taps_occupied": 58, …
```
=> Add a naive beer autocomplete endpoint

venues/serializers.py, venues/test/test_views.py, venues/urls.py, venues/views.py
API endpoint: `/api/v1/venues/byslug/my-bar/`
=> Add ability to look up a venue by slug

beers/tasks.py, tap_list_providers/parsers/untappd.py, venues/admin.py, venues/fixtures/venues.json
Also automatically retry untappd lookup for newly created beers.
=> Add Rocket City Brewfest

tap_list_providers/parsers/untappd.py, venues/fixtures/venues.json
This partially reverts commit ed7098975a9c719c379e960c63024f53f289634f.
=> Drop RCBF since it's done until 2020

tap_list_providers/base.py
Fix Bell's Official somehow breaking the beer lookup in DigitalPour.
=> Fix Bell's Official breaking DIgitalPour

tap_list_providers/parsers/untappd.py, tap_list_providers/test/test_untappd_blank_name.py
=> Fix the handling of Reissdorf Kölsch

venues/fixtures/venues.json
=> Remove Wish You Were Beer

beers/tasks.py, beers/test/test_tasks.py
Just make our celery logs a bit cleaner
=> Don't raise an exception if we run out of retries

taps/admin.py
=> Make tap admin list work better

beers/filters.py, beers/test/test_views.py, beers/views.py
=> Enable sort by recently tapped

venues/test/test_views.py, venues/views.py
The lookup for the `beers/` detail route of the venue by slug lookup was failing because Django was trying to pass the `slug` kwarg to a method that was expecting `pk`. Fix that by overriding the parent class's detail route.
Yeah, it's a little non-DRY, but it works for a band-aid. I'll clean it up later.
Addresses #236.
=> Fix 500 error on /api/v1/venues/byslug/my-bar/beers/

venues/views.py
I'm not going to be able to easily finish #236 until https://github.com/philipn/django-rest-framework-filters/issues/287 is complete, so I'm going to push up this fix before I forget.
=> Make the slug lookup a little more DRY

hsv_dot_beer/config/production.py
Based on https://github.com/adamchainz/django-cors-headers#cors_origin_regex_whitelist
=> Whitelist all https://*.herokuapp.com

beers/filters.py, beers/test/test_views.py
Fixes #264 by creating a subclass of OrderingFilter that treats ABV as a special case and uses Django's `nulls_first` and `nulls_last` arguments as appropriate.
=> Sort null ABVs as if they were zero

Pipfile.lock
=> Bump Django to 2.2.6

docker-compose.yml
This only affects dev, not production, but it's good to keep
ourselves current
=> Bump PostgreSQL to 11.5

README.md
=> Add some clarifying notes to the README

docker-compose.yml
=> Bump PostgreSQL to 12.0

venues/fixtures/venues.json
This is the replacement for Keegan's. I haven't seen anything on
the web at all from them, so I have no idea if they're closing at
all to do any remodeling.
Addresses #181.
=> Add Big Spring Tavern to our venues

tap_list_providers/tasks.py
=> Switch back to 'New:' as the new line prefix

tap_list_providers/tasks.py
This reverts commit bcfc3739db14b6e26c8223790d30487fd727f872.
=> Use `-` as new line prefix

venues/fixtures/venues.json
=> Add Twitter handle for Madison Taproom

beers/admin.py
1. Sort styles and manufacturers alphabetically in the beer admin page
2. Show beer styles in the beer admin list so we can easily sort by beers missing a style
=> Beer admin improvements

venues/fixtures/venues.json
=> Add Rocket Republic Downtown's new Twitter account

venues/fixtures/venues.json
=> Add missing underscore in RR Downtown's twitter handle

Pipfile.lock
Fixes a Django password reset security bug in 3.0
=> Version bump packages

venues/fixtures/venues.json
=> Fix Beauregard's categories

Pipfile.lock
=> bump dependencies

tap_list_providers/tasks.py
=> Log tweet that caused Twitter error

Pipfile, Pipfile.lock, hsv_dot_beer/config/production.py, hsv_dot_beer/test_cache.py
Also add a unit test to make sure our config is never bogus again.
Fixes #307.
=> Upgrade to bmemcached 0.3.0

tap_list_providers/tasks.py, tap_list_providers/test/test_tweets.py
=> Don't tweet about beers if they're not on tap

Pipfile.lock
It's a security patch that doesn't affect us.
=> Upgrade Django to 3.0.4

Pipfile.lock, bin/release.sh
Hopefully this will make Heroku rebuild the virutalenv and maybe
explain why things magically broke
=> Version bump

tap_list_providers/base.py
Fixes Madison Taproom failing to look up MIA's Neon Citra White IPA
=> Add ratebeer to the list of unique fields

.github/actions/lint/Dockerfile, Dockerfile, Pipfile, Pipfile.lock, beers/filters.py
Trying again, this time to see if github can figure it out
=> Upgrade to Python 3.8

beers/models.py
=> Add a missing comma that was causing excluded fields to be wrongly kept

tap_list_providers/example_data/beermenus/64594-bad-daddy-s-burger-bar-huntsville.html, tap_list_providers/parsers/beermenus.py
This caused two problems:
1. A price without a serving size
2. No beer link meant we couldn't get more info on it
As a result, let's skip it.
=> Catch Bad Daddy's putting a shake in the featured list

beers/tasks.py, tap_list_providers/tasks.py
This will make the console output less noisy.
=> Don't raise exceptions if in local dev and untappd creds aren't set

venues/fixtures-al/venues.json
=> Add Braided River

venues/fixtures/venues.json
They're closing Sunday: https://www.waaytv.com/content/news/Two-Huntsville-businesses-closing-due-to-loss-of-revenue-during-the-pandemic-573361801.html
=> Drop Beauregard's from fixtures list

tap_list_providers/parsers/untappd.py, venues/fixtures-al/venues.json, venues/fixtures/venues.json
Confirmed that they do not use Twitter and that they want to use the gobeezr website as their website. Also Chad Emerson with Downtown Huntsville said they would "very soon" officially be on the Downtown Huntsville Craft Beer Trail.
=> Add Chandler's Ford Brewing

Pipfile.lock
Django security update plus a few other minor things
=> Bump versions

Pipfile.lock
Nothing fancy here, just some small stuff
=> Minor dependency upgrades

tap_list_providers/parsers/untappd.py
They have 16.9 ounce pours because why not?
=> Support 16.9 oz pours from Chandlers Ford

hsv_dot_beer/users/test/test_views.py, tap_list_providers/example_data/chattahoochee.html, tap_list_providers/parsers/untappd.py, tap_list_providers/test/test_chattahoochee.py, tap_list_providers/test/test_goat_island.py
=> Delete taps that aren't in use if we don't have sequential tap numbers

tap_list_providers/example_data/cahaba.json, tap_list_providers/parsers/arryved_pos.py, tap_list_providers/test/test_arryved_pos.py
Cahaba Queen of Hops is 5.6 IBU on their system, so let's round to 6.
=> Round Arryved POS IBUs

venues/fixtures/venues.json
=> Drop Rocket City Craft Beer from the fixtures

Dockerfile, Pipfile.lock, fly.toml
Basic changes to deploy to fly.io and have the API be browseable. Parser fixes coming later.
=> Deploy to fly dot io

tap_list_providers/parsers/taphunter.py, tap_list_providers/test/test_wagon_wheel_gallon.py
=> Fix handling 1 gallon serving sizes from Wagon Wheel

Dockerfile, bin/entry-point.sh
=> Update docker container to run the entry point script

tap_list_providers/example_data/goat-no-brewery.html, tap_list_providers/parsers/untappd.py
Also catch the tap number being missing from the HTML
Fixes #440
=> Fall back to the venue name if one isn't provided in the HTML

tap_list_providers/example_data/wagonwheel_1_gal.json, tap_list_providers/test/test_goat_island_without_brewery.py, tap_list_providers/test/test_wagon_wheel_gallon.py
=> Add tests I forgot to commit

venues/fixtures-al/venues.json, venues/fixtures/venues.json
=> Drop Fractal and Whole Foods from our venues list

Pipfile, Pipfile.lock, beers/admin.py, beers/test/test_merge.py, beers/test/test_untappd_rate_limit.py, events/test/test_serializers.py, tap_list_providers/parsers/arryved_menu.py, tap_list_providers/parsers/beermenus.py, tap_list_providers/parsers/digitalpour.py, tap_list_providers/parsers/stemandstein.py, tap_list_providers/parsers/taphunter.py, tap_list_providers/parsers/untappd.py, tap_list_providers/test/test_untappd.py, venues/fields.py, venues/test/factories.py, venues/test/test_serializers.py, venues/test/test_views.py
=> Upgrade to Django 4.0

fly.toml
=> migrate to fly apps v2

tap_list_providers/base.py, tap_list_providers/test/test_base.py
=> Fix processing Weihenstephan from OTBX

hsv_dot_beer/config/production.py
Like #478 but without the migrations because those break all our filtering
=> Fix storage definition for Django 4.2
